### ISSUE TITLE
F4 on blank page closes application

### ISSUE THREAD

**Issue by andrzejchmiel3** [KrzysztofDusko/JustyBase#278]
Pressing F4 in empty document (before typing any SQL code) closes application

**Comment by KrzysztofVl** [comment]
```c#
AAA-BBB_1 - MESSAGE:
    0 <= index < 3 (Parameter 'index')
Actual value was -1.
STACKTRACE:
   at AvaloniaEdit.Utils.Rope`1.get_Item(Int32 index) in E:\source\repos\AvaloniaEdit\src\AvaloniaEdit\Utils\Rope.cs:line 484
   at JustDataEvoShared.Helpers.EditorHelpers.GetSurrendedText(TextArea textArea) in E:\source\repos\JustDataEvoProject\JustDataEvo.Shared\RoslynHelpers\EditorHelpers.cs:line 171
   at JustDataEvo.ViewModels.Documents.SqlDocumentViewModel.GetTappedWord() in E:\source\repos\JustDataEvoProject\JustDataEvo.Shared\ViewModels\SqlDocumentViewModel.cs:line 263
   at JustDataEvo.Views.Documents.SqlDocumentView.TextEditor_KeyDownAsync(Object sender, KeyEventArgs e) in E:\source\repos\JustDataEvoProject\JustDataEvoMulti\Views\Documents\SqlDocumentView.axaml.cs:line 132
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at JustDataEvo.Program.Main(String[] args) in E:\source\repos\JustDataEvoProject\JustDataEvoMulti\Program.cs:line 52
```

**Comment by KrzysztofDusko** [comment]
fixed
