### ISSUE TITLE
JustyBase - Undo sometimes fails

### ISSUE THREAD

**Issue by KrzysztofDusko** [KrzysztofDusko/JustyBase#309]
to reproduce

1. paste image (of course will not be pasted) 
2. try to undo this operation
3. Exception occurs

```
AAA-BBB_1
    MESSAGE
        No undo group should be open at this point
    STACKTRACE
           at AvaloniaEdit.Document.UndoStack.ThrowIfUndoGroupOpen()
   at AvaloniaEdit.Document.UndoStack.Undo()
   at AvaloniaEdit.Editing.TextAreaDefaultInputHandler.ExecuteUndo(Object sender, ExecutedRoutedEventArgs e)
   at AvaloniaEdit.RoutedCommandBinding.DoExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at AvaloniaEdit.RoutedCommand.ExecutedEventHandler(Interactive control, ExecutedRoutedEventArgs args)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at AvaloniaEdit.Editing.TextAreaInputHandler.TextAreaOnKeyDown(Object sender, KeyEventArgs keyEventArgs)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at JustDataEvo.Program.Main(String[] args)
```

**Comment by KrzysztofDusko** [comment]
related to 
https://github.com/AvaloniaUI/AvaloniaEdit/issues/398

**Comment by KrzysztofDusko** [comment]
fixed ? - real world test needed
